# Generated by Django 5.2.7 on 2025-10-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'Hall',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.genre')),
            ],
            options={
                'db_table': 'Play',
            },
        ),
        migrations.CreateModel(
            name='Playactor',
            fields=[
                ('pk', models.CompositePrimaryKey('play_id', 'actor_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.actor')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.play')),
            ],
            options={
                'db_table': 'PlayActor',
            },
        ),
        migrations.CreateModel(
            name='Playdirector',
            fields=[
                ('pk', models.CompositePrimaryKey('play_id', 'director_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.director')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.play')),
            ],
            options={
                'db_table': 'PlayDirector',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.hall')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.play')),
            ],
            options={
                'db_table': 'Schedule',
                'unique_together': {('play', 'hall', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Theatre',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.theatre'),
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('theatre', 'name')},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
            ],
            options={
                'db_table': 'Ticket',
                'unique_together': {('schedule_id', 'seat')},
            },
        ),
    ]
